# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarTrivia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarTrivia
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire'

  target 'StarTriviaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarTriviaUITests' do
    # Pods for testing
  end

end
